Feature/workspaces
samply/open-telekom-cloud pull request #10
Opened 2019-08-27 08:18 UTC by martinbreu

Dieser PR dient erstmal zur einfacheren Zusammenarbeit.

2019-08-27 08:36 UTC, alexanderkiel reviewed
Looks good, but we have to test it. So I'll ask ML to set the Domains, so Let's Encrypt can see us.

2019-08-27 12:09 UTC, martinbreu commented
`terraform plan` looks fine, should we try `terraform apply` together at https://whereby.com/biocoders ?

2019-08-29 08:09 UTC, martinbreu commented
`terraform apply`:
```
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [5m20s elapsed]
module.postgres.opentelekomcloud_rds_instance_v3.postgres: Creation complete after 5m22s [id=ecfbce3524c94d2489ad8dfbf6b3cbf6in03]
module.postgres.opentelekomcloud_dns_recordset_v2.postgres: Creating...
module.postgres.opentelekomcloud_dns_recordset_v2.postgres: Creation complete after 6s [id=ff8080826c8f5cf2016cdc5fe93c4208/ff8080826c8f5c5c016cdc64e3d54f38]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [5m30s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [5m40s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [5m50s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [6m0s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [6m10s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [6m20s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [6m30s elapsed]
module.server.opentelekomcloud_compute_instance_v2.server: Still creating... [6m40s elapsed]


Error: timeout - last error: dial tcp :22: connect: connection refused


martinbreu@nful050x:~/Repositories/itc/open-telekom-cloud$ 
```
Server wurde erstellt, keine EIP zugewiesen

2019-08-29 11:00 UTC, martinbreu commented
```
module.postgres.opentelekomcloud_rds_instance_v3.postgres: Still creating... [5m10s elapsed]
module.postgres.opentelekomcloud_rds_instance_v3.postgres: Creation complete after 5m19s [id=2cfc2ca37fcd4a2e92041653169cee38in03]
module.postgres.opentelekomcloud_dns_recordset_v2.postgres: Creating...
module.postgres.opentelekomcloud_dns_recordset_v2.postgres: Creation complete after 6s [id=ff8080826c8f5c5c016cdd015f67543f/ff8080826c8f5c5c016cdd065d54546a]

Error: Upload failed: scp: /mnt/secrets/searchbroker-ui: Permission denied


martinbreu@nful050x:~/Repositories/itc/open-telekom-cloud$ 
```

2019-10-01 07:17 UTC, martinbreu commented
Anyhow, we need to switch at least the database between dev and prod freely. I would suggest a manuel way

2019-10-02 16:31 UTC, alexanderkiel commented
Still work in progress

2019-10-09 15:15 UTC, alexanderkiel requested changes

2019-10-09 15:15 UTC, alexanderkiel commented on modules/server/main.tf
> +  searchbroker_version    = "3.3.0-SNAPSHOT"
SNAPSHOT should go before finalizing this

2019-10-31 10:25 UTC, martinbreu commented
All services run as expected

2019-11-04 13:04 UTC, alexanderkiel approved these changes

2019-11-04 13:31 UTC, merged