Updated MDR images to fix log4j problem
samply/open-telekom-cloud pull request #81
Opened 2022-02-23 12:10 UTC by DavidCroftDKFZ

Note that image names have changed since martinbreu.

DB schema should not have changed, so existing MDRs can simply be
restarted with the new images, but database backup is advised just in
case.

Also, I have used absolute versions. Please advise if more flexible
versioning is required.

2022-02-23 12:42 UTC, torbrenner submitted a review, later dismissed

2022-02-23 12:45 UTC, torbrenner commented
The Versions used by you should be updated with new Code Versions merged into master.

2022-03-07 11:27 UTC, torbrenner approved these changes

2022-03-07 12:18 UTC, alexanderkiel requested changes

2022-03-07 12:18 UTC, alexanderkiel commented on modules/server/main.tf
> +  mdr_version    = "release-gba-mdr"
I don't like to deploy floating releases. Some kind of version would be highly appreciated.

2022-03-07 12:18 UTC, alexanderkiel commented on modules/server/main.tf
> +  mdr-ui_version = "master"
Same here.

2022-03-07 15:36 UTC, alexanderkiel commented on modules/server/main.tf
> +  mdr_version    = "release-gba-mdr"
We decided to take the risk.

2022-03-07 15:36 UTC, alexanderkiel commented on modules/server/main.tf
> +  mdr-ui_version = "master"
We decided to take the risk.

2022-03-07 15:36 UTC, alexanderkiel approved these changes

2022-03-09 13:30 UTC, merged